### ISSUE TITLE
test.fga.db is not removed after running tests

### ISSUE THREAD

**Issue by MeAmAnUsername** [ProgrammingLife2017/Desoxyribonucleinezuur#121]
Currently on branch: mapdb

introduced somewhere around commit dae922d326a561fbd15085501aed31516aef320c
probable cause: name does not match the name used to remove the file by `DataManager.removeDB(String)`
Underlying issue: name at creation should be converted to test.db, but it isn't.
Probable location: somewhere in GUIControllerTest or DataManager.

To reproduce:
Run tests in GUIControllerTest
There is now a file named test.fga.db in the root directory

Expected behaviour:
The file is removed after testing (and would be named test.db in the first place).

**Comment by YDutchy** [comment]
Closed by #155
