### ISSUE TITLE
maxInt in bookmark

### ISSUE THREAD

**Issue by IwanHoogenboom** [ProgrammingLife2017/Desoxyribonucleinezuur#163]
When you create a bookmark with a radius bigger than the 32bit max int the program will not do anything. No error, no exception.

**Comment by toinehartman** [comment]
For me, `parseInt` raises an Exception that it is not an int, which is catched by showing an alert. So, no problem for me.

**Comment by MeAmAnUsername** [comment]
Also doesn't work for me (read as: everything happens as described in the original error).

Suggested fix: catch NumberFormatExceptions and fail the bookmark creation (number could not be parsed)
Or, parse as long and then downsize to int (show message when int is not big enough)

**Comment by YDutchy** [comment]
Has been solve by the pull request for bookmarks
