### ISSUE TITLE
Console slows down program

### ISSUE THREAD

**Issue by MeAmAnUsername** [ProgrammingLife2017/Desoxyribonucleinezuur#171]
When console has a lot of lines, it severely slows down the program when it is visible.

Probable cause: JavaFX text fields are not made to contain a lot of text, and therefore it becomes slow.

proposed solutions:
 - limit the amount of text in the console (by lines and/or characters)
 - run the console on another thread.

**Comment by toinehartman** [comment]
I do not experience this. How can I reproduce it?

**Comment by toinehartman** [comment]
Closed by #183.
