### ISSUE TITLE
Implement commands for console

### ISSUE THREAD

**Issue by MeAmAnUsername** [ProgrammingLife2017/Desoxyribonucleinezuur#173]
So that the program can be used without the mouse
some commands:

Meta: 
 - `foo` is literal text: `foo`
 - `<foo>` is a parameter, which is replaced with another value in the command: `45`
 - `{ A | B }` is a choice: `A`
 - `bar [foo]` is an optional parameter: `bar` or `bar foo`
example: `foo {<name> | [bar] <ID>}` => `foo a_name` or `foo bar 6` or `foo 6`

`<Node>` means `{<ID> | {<name> | <index>} <coordinate>}`, which is the node with id ID, or the node with <coordinate> in the genome with name <name> or the genome on index <index>

 - `node [<Node>]`: show information about the node, or the centerNode if there is no node specified.
 - `sequence [<Node>]`: show the sequence within node, or the centernode if no node was specified.
 - `goto <Node>`: show node on the screen
 - `left [<X>]`: go X steps left (or 1 if no number specified)
 - `right [<X>]`: go X steps right (or 1 if no number specified)
 - `right [<X>]`: go X steps up (or 1 if no number specified)
 - `down [<X>]`: go X steps down (or 1 if no number specified)
 - `edge <ID1> <ID2>`: show info about the edge from ID1 to ID2
 - `path <ID1> <ID2>`: show the nodes in the path from ID1 to ID2
 - `bookmark <name> {current | <ID> [<radius>]} <description>`: Add a bookmark with <name>, either at the current position or at the node ID (with possible radius), and a description.
 - `genomes`: show the names of all geomes (and also the number?)
 - `genome <name>`: show info (nodes?) from a genome.

**Comment by MeAmAnUsername** [comment]
This would also enable scripting, which would probably not be that useful for users, but it would be useful for testing

**Comment by toinehartman** [comment]
Won't fix.
