### ISSUE TITLE
Tests fail consistently on my machine

### ISSUE THREAD

**Issue by MeAmAnUsername** [ProgrammingLife2017/Desoxyribonucleinezuur#176]
just like #59, I seem to be the only one who has this, so I think it because of not-too-robust file loading / deleting.

The tests that fail are BookmarkControllerTest and GuiControllerTest.
GuiControllerTest seems to pass if it is run first.

**Comment by YDutchy** [comment]
If all has been updated accordingly this should have been fixed now.
