### ISSUE TITLE
Improve the bookmark window

### ISSUE THREAD

**Issue by YDutchy** [ProgrammingLife2017/Desoxyribonucleinezuur#179]
Comments given by other on what might improve the bookmarks:

- [x] It would be nice if a bookmark could be opened on double-clicking it.
- [x] It would be nice if the bookmarks pane for the current window would be opened by default on opening the window.
- [ ] It would be nice if all relevant node info is shown on the side when selecting a node, i.e. don't have to click a button
- [x] Please add some padding around the buttons.
- [x] When I delete a bookmark the dropdownfolderthingy closes, making me have to open it again to select another bookmark.
- [x] When I have the bookmarkwindow open and I want to make a bookmark with the quickcreate button the bookmark does not show up if I do not reopen the bookmark window.
- [ ] Make columns scale with contents (long names are truncated).
- [ ] It would be nice to be able to select multiple bookmarks / whole graphs to be deleted at once. Possibility: click delete, mark all bookmarks to be deleted, confirm.
- [ ] Make bookmarks editable
- #180

**Comment by YDutchy** [comment]
I think the open and delete buttons should be active when you haven't loaded a graph. In my opinion users should be able to always use these

**Comment by toinehartman** [comment]
This is true, but it is about a bookmark being selected or not.
