### ISSUE TITLE
Feedback sprint 5

### ISSUE THREAD

**Issue by lkrombeen** [ProgrammingLife2017/Desoxyribonucleinezuur#185]
**sprint planning**:
- Some issues e.g. #167 have no single responsibility, no description and do not link back to the user story.
- #169 is in progress but has no assignees. The description makes it feel like the issue should be split.
- Good use of labels. Time estimations are clear and the prioritization is good.
- The project board could be updated better. For example, I really hope you closed #174 (I was grading on the 27th).
- Splitting can be improved. Ivo has a total of 81.5 hours assigned, Toine only 20.5. Are you updating your time tables on issues that for example take 20 hours? I saw a similar thing happening last week where someone was assigned 41 hours but spent 20 hours according to the retroperspective. So I think your time labels should be updated ;)
- Ivo only worked 2.5 hours according to your retroperspective.
- Write down the reason why a task was not finished. Also when the decision was made to not work on it at all.
**code evaluation**
- No commits directly in master, good.
- Issues closed this week have proper discussions inside them. Same goes for PRs
- Keep your architecture design up to date.
- Your project contains some warnings e.g. unused imports.
+- 62% test branch coverage.
- Indicate what behaviour you are testing when writing the tests for complex behaviour / corner cases e.g. using documentation above the testing method.
- Do not use generic exceptions.
- There are some duplicate definitions e.g. “Bookmark”, “graph”. Define them as constants instead.
- There are some new complex methods in GraphParser and Bookmark.
- BookmarkController has duplicated code.
- Return an empty list instead of null in parseBookmarks

**Comment by IwanHoogenboom** [comment]
Issues with label UserStory are seen as a big overall feature, these should be divided into small issues. This means that if an issue has the UserStory label we do not count the time assigned to it, but only count the small(er) sub-issues. Retrospective only uses the smaller issues which summed should add to the time that is indicated in the UserStory.
