### ISSUE TITLE
Make topo sort fast again!

### ISSUE THREAD

**Issue by IwanHoogenboom** [ProgrammingLife2017/Desoxyribonucleinezuur#188]
We want to have a fast topo sort. Like really fast. Faster than fast and furious 8 fast. 

![2017-05-31 17_17_09-](https://cloud.githubusercontent.com/assets/9801656/26639456/2a581654-4625-11e7-8ea6-521714089d68.png)

We did a benchmark which shows that topo sort takes a long time when drawing. The time is in ms and the longest one is drawing 1000 nodes.

**Comment by toinehartman** [comment]
Closed by #196.
