### ISSUE TITLE
Minimize edge crossings

### ISSUE THREAD

**Issue by MeAmAnUsername** [ProgrammingLife2017/Desoxyribonucleinezuur#209]
There are currently too many crossings between edges. We should minimize them or completely eliminate them if possible in reasonable time.
This minimizing should be implemented in `SubGraph.sortLayers()`

**Comment by MeAmAnUsername** [comment]
The TAs said it should be reasonably possible with a greedy algorithm over the layers.
I don't think that it can always be done perfectly that way, but I do believe it would perform reasonably well, and a pro is that it can be used to dynamically increase the subgraph.

**Comment by MeAmAnUsername** [comment]
For #127

**Comment by mvanmeerten** [comment]
closed by #235.
