### ISSUE TITLE
Node visuals

### ISSUE THREAD

**Issue by MeAmAnUsername** [ProgrammingLife2017/Desoxyribonucleinezuur#210]
Have a way to change the color for specific nodes.
Note: this is only about having the interface for drawing a set of nodes in the specified way, i.e.: 
input: set of nodes, way to be drawn / category they belong to
output: Nodes are drawn to screen in specified way when `GraphController.draw()` is called
The actual input for this interface comes from #215 

Uses:
- [x] highlight the centernode (the node that was intentionally searched for, via left menu or bookmarks) #225 
- [x] highlight paths from annotations
- [x] color nodes satisfying certain conditions
   - mark all nodes in a bookmark / annotation
   - show all nodes with more than X number of parents / children
   - show all nodes with a certain attribute

Options:
 - color inside nodes
 - color node border
 - multiple colors / overlay colors: for when multiple things go through the same node, like multiple annotations / multiple bookmarks.
 - gradients, example use: grey: less genomes <==> blue: more genomes
 - opacity: example: less genomes: (almost) invisible <==> more genomes: opaque

**Comment by MeAmAnUsername** [comment]
For #214

**Comment by mvanmeerten** [comment]
I would suggest thickness of nodes and edges to represent the amount of genomes through a node or edge. This leaves color to purely signify the contents of sequences eg. ratio of AT to GC pairs
