### ISSUE TITLE
Find paths

### ISSUE THREAD

**Issue by MeAmAnUsername** [ProgrammingLife2017/Desoxyribonucleinezuur#211]
Input: start node ID, end node ID

Important note: start and end node might not be in the same genome!

Possible outputs:
 - shortest path from start to end
 - any path from start to end
 - all genomes that have a path from start to end (EZ PZ: for each genome, check if start comes before end and end is also in genome)
 - all paths from start to end (requires full graph toposort?)

**Comment by MeAmAnUsername** [comment]
Note: this issue is for handling annotations in milestone 5

**Comment by MeAmAnUsername** [comment]
for #214

**Comment by toinehartman** [comment]
Not necessary anymore as annotations will not be implemented.
