### ISSUE TITLE
edge visuals

### ISSUE THREAD

**Issue by MeAmAnUsername** [ProgrammingLife2017/Desoxyribonucleinezuur#212]
Give the possibility (an interface somewhere) to change the visual aspects for (a set of) edges.

uses:
 - show specific paths (like annotations)
 - show edge attributes, like number of genomes

Options:
 - edge thickness
 - edge color (hue, saturation)
 - opacity

**Comment by MeAmAnUsername** [comment]
For #214

**Comment by mvanmeerten** [comment]
closed by #236
