### ISSUE TITLE
GUI input window for filtering/searching specific nodes

### ISSUE THREAD

**Issue by MeAmAnUsername** [ProgrammingLife2017/Desoxyribonucleinezuur#215]
I imagine it would be a panel on the right, but that's not set in stone.
The goal is to find all nodes satisfying some criteria, and then show and highlight them in the graph. See also issue #210 

Must have:
 - [x] filter based on genomes
   - it cannot simply be a list of genomes. It might be viable if it is a list that can be filtered with a text field.
   - also allow regex? (ABC matches ABC, ABCD, ABCE, ABCDE, QABC?)
 - [x] filter based on ID
   - exact ID
   - allow partial matches? ("56" matches 56, 560, 156?)
   - greater than, less than, between? (id between 1 and 20)
 - [ ] filter based on genome and coordinate

Should have:
 - [ ] find in full graph or only on screen
 - [ ] show a table of matching nodes (on top of highlighting matching nodes). This is a requirement for filtering in the whole graph.
 - [ ] inversion: "find all nodes not in these genomes", "find all nodes with ID not between 10 and 10000"

Could have:
 - [ ] match on radius: find all nodes within radius X of nodes matching criteria...
 - [ ] nodes in annotation(s)...
 - [ ] match on path: give start node (via some method) and end node (via some method) and match all nodes on this path
   - [ ] give an option to match on any path, shortest path, nodes on path must share (any / user-specified) genome(s) (share genome means that all nodes on the path must be in (share) a single genome)
   - see also #211 
 - [ ] match on multiple filters at once, possibly using some pretty flexible matches (I personally quite like the way iTunes smart lists give the option to use complex statements, which is still pretty user friendly). 
   - this will probably require some thinking ahead, like making an interface `Matcher` with method `public Set<Node> match()` and `public matchLine getMatchLine()` so that matches can easily be nested (matchOnAny, matchOnAll, matchOnNone, matchNode, matchGenome, matchPath...). `getMatchLine()` returns a `MatchLine` Object, which represents Strings, dropdown menus, buttons and input fields and that can be "printed" to the GUI. Warning: this solution is very OOP. Use at your own risk.

Example of all features combined (Note: also have for all conditions a button to the left / right to remove that condition):
```
Explanation of "grammar":
_[foo|**bar**]_: dropdown menu with options foo and bar, bar is selected
`faz`: button with text "faz"
**bog**: text/number input field.
Note: lines change based on selected options earlier in the line.
```
```
Select nodes _[in the whole graph|from the nodes on the screen]_ matching the following criteria:
_[**Any**|All|None]_ of:
  _[Any|**All**|None]_ of:
    _[**Node id**|Genome|Node with coordinate|Nodes are on path]_ _[**between (inclusive)**|greater than|exactly|less than]_ **10** and **50**
    _[Node id|**Genome**|Node with coordinate|Nodes are on path]_ _[**is**|matches]_ **ABC** (Note: when entering input in text field, list with matching genome names pops up underneath as suggestions)
    `Add a new condition that must be met`
  _[Any|**All**|None]_ of:
    _[Any|All|**None**]_ of:
      _[Node id|**Genome**|Node with coordinate|Nodes are on path]_ _[matches **XYZ**
      `Add a new condition that must be met`
    _[Node id|Genome|Node with coordinate|**Nodes are on path**]_ _[any|all|**none**|shortest]_ of the paths from node with _[**id**|base]_ (Note: can be selected by clicking)] **3040** to node with _[id|**base**]_ **2349871** in _[**genome**|path]_ named **AKCDR** 
      that include the node with _[**id**|base]_ **3050**
      `Add conditions that path must meet` (options: contains node ..., contains genome ..., is in any genome (matching ...))
  `Add a new condition that must be met`
`Add a new condition that would also match nodes`
```

**Comment by IwanHoogenboom** [comment]
Things not implemented wont be implemented anymore.
