### ISSUE TITLE
GUI onclick info

### ISSUE THREAD

**Issue by MeAmAnUsername** [ProgrammingLife2017/Desoxyribonucleinezuur#217]
When clicking on an edge or node, there should be some information about that it in the window of the main application, not just in the console. I suggest this information is shown in a sidebar somewhere, possibly the same one as for #215 (switch via tabs or some other means).
This information should preferably be copyable.

In general: if the list of genomes / annotations / bases is too big, it should be truncate with something like `bar, foo, ... (15 more)`, and have some way to view the truncated bit.

Information that should be shown:
- for nodes:
  - ID
  - number of incoming / outgoing edges.
  - sequence
  - genomes
  - part of annotations... (for milestone 5)
- for edges:
  - parent node
  - child node
  - genomes
  - part of annotations... (for milestone 5)

**Comment by YDutchy** [comment]
Closed by #233
