### ISSUE TITLE
Feedback sprint 6 

### ISSUE THREAD

**Issue by lkrombeen** [ProgrammingLife2017/Desoxyribonucleinezuur#223]
**sprint planning:**
- Make adjustments in your retroperspective if the sprint did not go as planned to ensure it will be better next week.
- There are some tasks that have not been finished without a description why. It looks like issues that are nice to do if there is time left, but make sure to mention that.
- Make clear who will do #221 even if someone is responsible for the user story.

**code evaluation**
- 60% test coverage.
- There are some problematic Travis builds following each other.
- Include some more descriptions for PRs.
- There are project warnings that can be easily fixed e.g. unused imports.
- Some commented code e.g. in DrawableEdge.
- Use Random.nextInt() to get a random number, not Math.random().
- “This file can’t be opened” occurs multiple times, define it as a constant.
- There are some complex methods. For example in BookmarkController and GraphParser.
- There are some unused fields e.g. INITIAL_OFFSET.
- getGenomes has an unused method parameter.
- The methods loadAllGraphBookmarks and bookMarkExists have a similar block of code.
- Any particular reason why you are using the Collection<? extends Edge> wildcards? It would be better to not use wildcards.
- Update the architecture design. It is outdated.

**Comment by MeAmAnUsername** [comment]
Any particular reason why you are using the Collection<? extends Edge> wildcards?
