### ISSUE TITLE
keyboard shortcuts

### ISSUE THREAD

**Issue by MeAmAnUsername** [ProgrammingLife2017/Desoxyribonucleinezuur#224]
Have keyboard shortcuts

- [x] ctrl+o: open file
- [x] ctrl+q: quit program
- [ ] ctrl+w: close graph
- [x] ctrl+b: open the bookmark window
- [ ] esc: cancel current operation
- [x] ctrl+h: open the help menu
- [x] ctrl+i: opens the information menu

**Comment by toinehartman** [comment]
Closing the graph and canceling an operation should not be done via keyboard shortcuts.
