### ISSUE TITLE
Minimize edge bends

### ISSUE THREAD

**Issue by MeAmAnUsername** [ProgrammingLife2017/Desoxyribonucleinezuur#232]
By having "holes" in the graph in between bubbles, so that edges don't have to fill the holes.

Example: 
![image](https://user-images.githubusercontent.com/15816455/26925171-002c7f08-4c49-11e7-898e-299aed5e5984.png)
The edge beneath the orange node should be straight before going up

**Comment by MeAmAnUsername** [comment]
Lower priority since Thomas said that the layout is good for now

**Comment by toinehartman** [comment]
Won't be fixed.
