### ISSUE TITLE
Parse GFF (annotation) files

### ISSUE THREAD

**Issue by MeAmAnUsername** [ProgrammingLife2017/Desoxyribonucleinezuur#244]
Using the datastructure interface from #243  

This should check that the genome names in the .gff file match those in the graph, and ask the user to match them if not. See also #248 
The best way (from usability perspective) would be ask as soon as a mismatch is found (and continue parsing in the background), but it might be easier to keep track of all unmatched genomes and bulk-ask the user after parsing.

For #242

**Comment by toinehartman** [comment]
A start is made in #272.
