### ISSUE TITLE
Bookmark current location

### ISSUE THREAD

**Issue by MeAmAnUsername** [ProgrammingLife2017/Desoxyribonucleinezuur#321]
The current location should be updated to be the actual current location, instead of just the location that was loaded.
It should somehow also save the radius / number of layers.

**Comment by mvanmeerten** [comment]
Radius / layers seems obsolete. More appropriate would be zoom level.

**Comment by IwanHoogenboom** [comment]
We have this now.

**Comment by IwanHoogenboom** [comment]
We dont have zoomlevel though but that is a won't fix.
