### ISSUE TITLE
On click highlight bug

### ISSUE THREAD

**Issue by IwanHoogenboom** [ProgrammingLife2017/Desoxyribonucleinezuur#331]
It did not work. Dont know how to reproduce the problem.

**Comment by mvanmeerten** [comment]
To reproduce:
On one node: both left- and right click. 
On another node: left or right click.
Expected result: both nodes highlighted.
Actual result: only the last node highlighted.

**Comment by YDutchy** [comment]
Martijn's bug has been fixed
