### ISSUE TITLE
Feedback Sprint Management Week 1

### ISSUE THREAD

**Issue by lkrombeen** [ProgrammingLife2017/Desoxyribonucleinezuur#4]
Here is the feedback for the first sprint. I will enter all your grades here so you can track your progress ;)
https://docs.google.com/spreadsheets/d/1CtztyF6JH_XaqPzJB7x5jpi1oTfi_4PVuT6HIjSam9Y/edit?usp=sharing

Some overall feedback:
- Who is assigned to which task?
- Who is (end-)responsible for what tasks?
- How are the tasks prioritized?
- What is the time estimation for the tasks?
- You could use labels to give a time estimation / priority to a task for a good overview. Github offers many tools that can help your process. Make sure to use them.
- Only add tasks that are relevant to the current sprint to the project and make sure your tasks are linked back to your user stories.
- Define your columns to represent the flow of the SCRUM process. For example, add a column ‘in progress’.
- You are supposed to spend 28 hours per person per week.
- Look at the rubrics for next week.
- Side note: it is no longer required to put every sprint in a new project board. Use one project board instead!

**Comment by MeAmAnUsername** [comment]
What does "responsibility" in the user stories mean?

**Comment by lkrombeen** [comment]
@MeAmAnUsername you can find it in the rubrics. It is defined as "Take responsibility as a team to deliver end result" e.g. make a single person responsible that a task gets completed, even when multiple people are assigned for the issue.
