### ISSUE TITLE
Clicking on edge for information

### ISSUE THREAD

**Issue by IwanHoogenboom** [ProgrammingLife2017/Desoxyribonucleinezuur#43]
When you click on an edge the ability to see which basepairs are connected with it.

**Comment by MeAmAnUsername** [comment]
"basepairs": did you mean "nodes"?

**Comment by MeAmAnUsername** [comment]
Also: show the genomes that go through this segment (if that is even possible)
The naive solution would be to find all genomes that are in both the begin and end node, but that doesn't work, counterexample:
[x, y, z] is a node from genomes x, y and z
```
[1, 2]--------[1,2]
       \      /
         [2]
```
Now, even though the upper edge connects two nodes from genome 2, it does not contain genome 2.
