### ISSUE TITLE
A basic GUI

### ISSUE THREAD

**Issue by IwanHoogenboom** [ProgrammingLife2017/Desoxyribonucleinezuur#7]
As a user, I want a GUI so that I can use the program without changing lines of code.
When I start the program 
Then a new window is opened for the program.
In this window it is possible to access functionality like (eg opening a file)

**Comment by IwanHoogenboom** [comment]
The GUI still needs some more buttons for parsing and drawing, so this issue can not be closed yet.

**Comment by YDutchy** [comment]
Alright. Good for reopening it then :)
